--- #YAML:1.0
name:                Dicop-Workerframe
version:             2.21
abstract:            Framework for creating workers for a DiCoP system
license:             BSD
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
