
=pod

=head1 Parallel execution/Multithreading

You can use perldoc to read this document: C<perldoc README>.

Last update: 2005-03-16

=head2 Overview

Not ready yet.

=head1 AUTHOR

(c) Bundesamt fuer Sicherheit in der Informationstechnik 1998-2005

The DiCoP Workerframe falls under the BSD license.

See the file LICENSE or L<http://www.bsi.de/> for more information.

=cut
