/*!
 * @file
 * @ingroup workerframe
 * @brief Dicop Project - Version, revision and last-modified information
 * 
 * @copydoc copyrighttext
 *  
 * @version v2.18 rev 545 
 * @date Fri Sep 14 10:42:14 2007 
 * @author Bundesamt f&uuml;r Sicherheit in der Informationstechnik (BSI)
*/

#ifndef DICOP_PATCH_H
#define DICOP_PATCH_H

/* This file is automatically modified to always reflect the newest
   patch level. Do not edit this file - all changes will be lost!

   Edit build/patch.tpl instead.
*/

/* version definitions:
   for Makefile.PL: 
$VERSION = "2.18"
*/

/** The version string for C code. */
#define DICOP_VERSION "v2.18"

/** The revision number. */
#define DICOP_REVISION "545"

/** The last-modified string. */
#define DICOP_MODIFIED "Fri Sep 14 10:42:14 2007"

#endif
